version: "3.8"

services:
  jira_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: jira_bot
    container_name: jira_bot
    volumes:
      - ./src/db/database.sqlite:/app/src/db/database.sqlite
    ports:
      - "5555:5555"
    restart: unless-stopped
